### ISSUE TITLE
DB authentication error

### ISSUE THREAD

**Issue by sean-kang** [pitkley/docker-netbox#10]
https://github.com/pitkley/docker-netbox/blob/6720d25405830a0692fa608ceb893cc7ab34e97b/entrypoint.sh#L39

As you can see above, it currently puts database name into user name. If you change database user name in database server, it will return DB authentication error.

To fix the problem, it should be changed to the following.

`sed -i "/# Database name/c\\    'NAME': '$DB_NAME'," configuration.py`

**Comment by pitkley** [comment]
@sean-kang good catch, thanks for opening the issue!

I have corrected the sed-command in PR #12 and have lifted the fix into `develop` with #13. The image-tags `develop` and `latest` are rebuilding on Docker hub as we speak.
