### ISSUE TITLE
Describe better how ALLOW_HOSTS works

### ISSUE THREAD

**Issue by isodude** [pitkley/docker-netbox#2]
I tried setting up netbox behind a haproxy.
- db and netbox share an internal network
- netbox and haproxy share an internal network.
- haproxy handles SSL-termination.
- haproxy is nated behind an IPv4 (which is internal as well).
- My client sits on an internal address and does not need to be translated to reach haproxy.

So my IP is 192.168.x.x and netbox is on 172.21.x.x, I can tcpdump the traffic and it comes from the haproxy on 172.21.y.y, obviously.

ALLOWED_HOSTS contains both 192.168.x.x and 172.21.y.y, however the app still blocks the request with response code 400.

Tried figuring out how python reacts to the requests and if it actually checks X-Forwarded-For, but it doesn't seem to be a more verbose command line argument for the managed.py file. It just doesn't print what IP the request is coming from.

**Comment by pitkley** [comment]
Can you try setting `ALLOWED_HOSTS = ['*']`? This should allow every host and thus allow your traffic. If that works, we can go debug this further!

Are you connecting to the HAProxy via IP or via hostname/domain name?

**Comment by isodude** [comment]
It worked fine by setting ALLOWED_HOSTS=*

I'm connecting through domain name since it's needed when connecting through HAProxy

**Comment by pitkley** [comment]
Try adding that domain-name to `ALLOWED_HOSTS`. As far as I know, that is what is actually checked and it's working for me that way.

**Comment by isodude** [comment]
Works perfectly. Maybe describe this a bit better in the README.md.

**Comment by pitkley** [comment]
I think this issue is more on theNetBox side of things rather than on this Docker image's side of things. Still, the documentation change in #3 makes sense.

Closing this "non"-issue for now.
